// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmifWIWttD4XkAYn6gL6yXeSnNtjdAXpA',
    appId: '1:614464401045:web:5dfacde944a586b6bef59c',
    messagingSenderId: '614464401045',
    projectId: 'proyecto-final-400122',
    authDomain: 'proyecto-final-400122.firebaseapp.com',
    databaseURL: 'https://proyecto-final-400122-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-final-400122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDBV-x3QMxPt6KWQUaV8sSuONYcHd83g',
    appId: '1:614464401045:android:88734beb5b75077cbef59c',
    messagingSenderId: '614464401045',
    projectId: 'proyecto-final-400122',
    databaseURL: 'https://proyecto-final-400122-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-final-400122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsOA3EbJbVuTFEOq377CXg4UyW4fAHHDc',
    appId: '1:614464401045:ios:00407965d997c088bef59c',
    messagingSenderId: '614464401045',
    projectId: 'proyecto-final-400122',
    databaseURL: 'https://proyecto-final-400122-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-final-400122.appspot.com',
    iosClientId: '614464401045-lrvqlr5c15othpbdbv7ii9d9ctrbpg2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.attempt1',
  );
}
