name: testing
description: "Rendición del software en estado de prueba"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '^3.2.0'


dependencies:
  date_time_picker: ^2.1.0
  firebase_auth_platform_interface: ^7.0.8
  firebase_core: ^2.3.0
  repositories:
    path: packages/repositories
  form_inputs:
    path: packages/form_inputs
  bloc: ^8.1.2
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.4.4
  firebase_auth_mocks: ^0.13.0
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
