name: repository
description: repositorios para todo lo que no es autenticacion
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.2
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  firebase_core_platform_interface: ^5.0.0
  json_serializable:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.4
